name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.23.3'

      - name: Install dependences
        run: sudo apt -y install libgpgme-dev libbtrfs-dev

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
