on:
  workflow_dispatch:
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04
    steps:
      - name: Install Dependencies
        shell: bash
        run: |
          podman run --privileged -it quay.io/podman/stable bash
          podman system service --time=0 unix:///tmp/podman.sock &
          podman run -it --security-opt label:type:container_runtime_t -v /tmp/podman.sock:/tmp/docker.sock:ro,z fedora:41 bash
          dnf install podman-remote -y
          podman-remote  --url unix:///tmp/docker.sock ps
          podman-remote  --url unix:///tmp/docker.sock run -it fedora:41 bash
