---
# GitHub workflow to run shellcheck on all *.sh files
on:
  pull_request:
  workflow_dispatch:
jobs:
  shellcheck:
    name: Run shellcheck on all *.sh files
    runs-on: ubuntu-22.04
    steps:
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run shellcheck
        shell: bash
        run: task shellcheck
